### ISSUE TITLE
<font size=3>  size is not working

### ISSUE THREAD

**Issue by helloHaifei** [SufficientlySecure/html-textview#60]
size is not working
`<p><font  size="2" color="#999999">good morning~</font><font>999</font></p>`

**Comment by monowar1993** [comment]
Did you solved this issue?

**Comment by carmas123** [comment]
+1

**Comment by coofeeing** [comment]
+1

**Comment by sunwaylife** [comment]
+1

**Comment by luchuantao** [comment]
+1

**Comment by izzyalonso** [comment]
The size attribute is ignored by Android:

- http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/5.1.1_r1/android/text/Html.java#825
- https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/text/Html.java#L1275

I ain't sure how up to date the aosp mirror is, but according to the file in grepcode the font tag only supports color and face attributes. This is probably just an error in this library's documentation.

Although limiting, a solution to this issue is using the `big` and `small` tags.

**Comment by AmiNadimi** [comment]
+1

**Comment by dschuermann** [comment]
Fixed the README. font size is not supported by Android's Html class.
I am open for pull requests to implement font size...
